services:
  - type: web
    name: playerstats
    env: node
    plan: free
    buildCommand: pip install -r requirements.txt && npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        sync: false # User will need to add this in the Render dashboard from Neon
